version: '1.0.0'

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=P@ssword
      - MYSQL_USER=Us&r
      - MYSQL_DATABASE=Db
    networks:
      - laravel
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html/projetoteste
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - db
  php:
    build:
      context: php/
      dockerfile: Dockerfile
    container_name: php
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html/projetoteste
    networks:
      - laravel
    depends_on:
      - nginx
      - db

networks:
  laravel: